
### GET REQUEST

GET http://localhost:8888/api/v1/users/68ae5ccaeb2dcae31f

### CREATE USER
POST http://localhost:8888/api/v1/users
Content-Type: application/json

{
  "user": {
    "email": "jdoe@example.com",
    "role": "MEMBER"
  }
}


### DELETE USER
DELETE http://localhost:8888/api/v1/users/68a8db157315cc435dfcf5f1
Content-Type: application/json

### EXISTS
GET http://localhost:8888/api/v1/users/exists?email=test@example.com
