### GET USER BY USER ID
GET http://localhost:8888/api/v1/users/JnM7sb9X91YE4cFF5VZ5yWUjKCj2
Content-Type: application/json


### CREATE USER
POST http://localhost:8888/api/v1/users
Content-Type: application/json

{
  "user": {
    "email": "jdoe@example.com",
    "role": "MEMBER"
  }
}


### DELETE USER
DELETE http://localhost:8888/api/v1/users/68a8db157315cc435dfcf5f1
Content-Type: application/json
